//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedActivities.Core.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lottie {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lottie() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharedActivities.Core.Resx.Lottie", typeof(Lottie).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;v&quot;: &quot;5.4.1&quot;,
        ///  &quot;fr&quot;: 1,
        ///  &quot;ip&quot;: 0,
        ///  &quot;op&quot;: 1,
        ///  &quot;w&quot;: 14,
        ///  &quot;h&quot;: 14,
        ///  &quot;nm&quot;: &quot;tick_green.ai&quot;,
        ///  &quot;ddd&quot;: 0,
        ///  &quot;assets&quot;: [],
        ///  &quot;layers&quot;: [
        ///    {
        ///      &quot;ddd&quot;: 0,
        ///      &quot;ind&quot;: 1,
        ///      &quot;ty&quot;: 4,
        ///      &quot;nm&quot;: &quot;tick_green Outlines&quot;,
        ///      &quot;sr&quot;: 1,
        ///      &quot;ks&quot;: {
        ///        &quot;o&quot;: {
        ///          &quot;a&quot;: 0,
        ///          &quot;k&quot;: 100,
        ///          &quot;ix&quot;: 11
        ///        },
        ///        &quot;r&quot;: {
        ///          &quot;a&quot;: 0,
        ///          &quot;k&quot;: 0,
        ///          &quot;ix&quot;: 10
        ///        },
        ///        &quot;p&quot;: {
        ///          &quot;a&quot;: 0,
        ///          &quot;k&quot;: [ 7, 7, 0 ],        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ScoringBad {
            get {
                return ResourceManager.GetString("ScoringBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;v&quot;: &quot;5.4.1&quot;,
        ///  &quot;fr&quot;: 1,
        ///  &quot;ip&quot;: 0,
        ///  &quot;op&quot;: 1,
        ///  &quot;w&quot;: 14,
        ///  &quot;h&quot;: 14,
        ///  &quot;nm&quot;: &quot;tick_green.ai&quot;,
        ///  &quot;ddd&quot;: 0,
        ///  &quot;assets&quot;: [],
        ///  &quot;layers&quot;: [
        ///    {
        ///      &quot;ddd&quot;: 0,
        ///      &quot;ind&quot;: 1,
        ///      &quot;ty&quot;: 4,
        ///      &quot;nm&quot;: &quot;tick_green Outlines&quot;,
        ///      &quot;sr&quot;: 1,
        ///      &quot;ks&quot;: {
        ///        &quot;o&quot;: {
        ///          &quot;a&quot;: 0,
        ///          &quot;k&quot;: 100,
        ///          &quot;ix&quot;: 11
        ///        },
        ///        &quot;r&quot;: {
        ///          &quot;a&quot;: 0,
        ///          &quot;k&quot;: 0,
        ///          &quot;ix&quot;: 10
        ///        },
        ///        &quot;p&quot;: {
        ///          &quot;a&quot;: 0,
        ///          &quot;k&quot;: [ 7, 7, 0 ],        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ScoringGood {
            get {
                return ResourceManager.GetString("ScoringGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;v&quot;: &quot;5.4.1&quot;,
        ///  &quot;fr&quot;: 1,
        ///  &quot;ip&quot;: 0,
        ///  &quot;op&quot;: 1,
        ///  &quot;w&quot;: 14,
        ///  &quot;h&quot;: 14,
        ///  &quot;nm&quot;: &quot;tick_green.ai&quot;,
        ///  &quot;ddd&quot;: 0,
        ///  &quot;assets&quot;: [],
        ///  &quot;layers&quot;: [
        ///    {
        ///      &quot;ddd&quot;: 0,
        ///      &quot;ind&quot;: 1,
        ///      &quot;ty&quot;: 4,
        ///      &quot;nm&quot;: &quot;tick_green Outlines&quot;,
        ///      &quot;sr&quot;: 1,
        ///      &quot;ks&quot;: {
        ///        &quot;o&quot;: {
        ///          &quot;a&quot;: 0,
        ///          &quot;k&quot;: 100,
        ///          &quot;ix&quot;: 11
        ///        },
        ///        &quot;r&quot;: {
        ///          &quot;a&quot;: 0,
        ///          &quot;k&quot;: 0,
        ///          &quot;ix&quot;: 10
        ///        },
        ///        &quot;p&quot;: {
        ///          &quot;a&quot;: 0,
        ///          &quot;k&quot;: [ 7, 7, 0 ],        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ScoringPerfect {
            get {
                return ResourceManager.GetString("ScoringPerfect", resourceCulture);
            }
        }
    }
}
