//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedActivities.Core.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lottie {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lottie() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SharedActivities.Core.Resx.Lottie", typeof(Lottie).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ScoringBad {
            get {
                return ResourceManager.GetString("ScoringBad", resourceCulture);
            }
        }
        
        public static string ScoringGood {
            get {
                return ResourceManager.GetString("ScoringGood", resourceCulture);
            }
        }
        
        public static string ScoringPerfect {
            get {
                return ResourceManager.GetString("ScoringPerfect", resourceCulture);
            }
        }
        
        public static string done_icon {
            get {
                return ResourceManager.GetString("done_icon", resourceCulture);
            }
        }
        
        public static string donePerfect_icon {
            get {
                return ResourceManager.GetString("donePerfect_icon", resourceCulture);
            }
        }
        
        public static string Thinking {
            get {
                return ResourceManager.GetString("Thinking", resourceCulture);
            }
        }
        
        public static string pointsIcon {
            get {
                return ResourceManager.GetString("pointsIcon", resourceCulture);
            }
        }
        
        public static string dialogue {
            get {
                return ResourceManager.GetString("dialogue", resourceCulture);
            }
        }
    }
}
