//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedActivities.Core.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class String {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal String() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SharedActivities.Core.Resx.String", typeof(String).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string CheckAnswersButton {
            get {
                return ResourceManager.GetString("CheckAnswersButton", resourceCulture);
            }
        }
        
        public static string FeedbackPerfect {
            get {
                return ResourceManager.GetString("FeedbackPerfect", resourceCulture);
            }
        }
        
        public static string FeedbackGood {
            get {
                return ResourceManager.GetString("FeedbackGood", resourceCulture);
            }
        }
        
        public static string FeedbackNotGood {
            get {
                return ResourceManager.GetString("FeedbackNotGood", resourceCulture);
            }
        }
        
        public static string PlusPoints {
            get {
                return ResourceManager.GetString("PlusPoints", resourceCulture);
            }
        }
        
        public static string NthAttemptBonus {
            get {
                return ResourceManager.GetString("NthAttemptBonus", resourceCulture);
            }
        }
        
        public static string PerfectScoreBonus {
            get {
                return ResourceManager.GetString("PerfectScoreBonus", resourceCulture);
            }
        }
        
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        public static string ExplainationTitle {
            get {
                return ResourceManager.GetString("ExplainationTitle", resourceCulture);
            }
        }
    }
}
