#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CrossLibrary.Droid.Resource", IsApplication=false)]

namespace CrossLibrary.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public static int fade_in_fast = 2130771968;
			
			// aapt resource value: 0x7F010001
			public static int fade_out_fast = 2130771969;
			
			// aapt resource value: 0x7F010002
			public static int none = 2130771970;
			
			// aapt resource value: 0x7F010003
			public static int slide_in_from_bottom = 2130771971;
			
			// aapt resource value: 0x7F010004
			public static int slide_in_from_left = 2130771972;
			
			// aapt resource value: 0x7F010005
			public static int slide_in_from_right = 2130771973;
			
			// aapt resource value: 0x7F010006
			public static int slide_in_from_top = 2130771974;
			
			// aapt resource value: 0x7F010007
			public static int slide_out_bottom = 2130771975;
			
			// aapt resource value: 0x7F01000A
			public static int slide_out_top = 2130771978;
			
			// aapt resource value: 0x7F010008
			public static int slide_out_to_left = 2130771976;
			
			// aapt resource value: 0x7F010009
			public static int slide_out_to_right = 2130771977;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F020000
			public static int containerId = 2130837504;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public static int default_activity_layout = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public static int app_name = 2130968576;
			
			// aapt resource value: 0x7F040001
			public static int hello = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F020000 }
			public static int[] CrossContainerView = new int[] {
					2130837504};
			
			// aapt resource value: 0
			public static int CrossContainerView_containerId = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
